//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CpcBaseProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int id { get; set; }
        public System.Guid TaskId { get; set; }
        public int Sort { get; set; }
        public string RoadName { get; set; }
        public string RoadStart { get; set; }
        public string RoadEnd { get; set; }
        public Nullable<decimal> RoadLength { get; set; }
        public Nullable<decimal> RoadWidth { get; set; }
        public string SidewalkStart { get; set; }
        public string SidewalkEnd { get; set; }
        public string SidewalkLength { get; set; }
        public string Memo { get; set; }
        public string StartX { get; set; }
        public string StartY { get; set; }
        public string EndX { get; set; }
        public string EndY { get; set; }
        public System.Data.Entity.Spatial.DbGeometry StartPoint { get; set; }
        public System.Data.Entity.Spatial.DbGeometry EndPoint { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Polygon { get; set; }
    }
}
